# Generated by Django 2.1 on 2019-04-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(default=None, max_length=12, primary_key=True, serialize=False, verbose_name='用户名')),
                ('password', models.CharField(default=None, max_length=100, verbose_name='密码')),
                ('nick_name', models.CharField(default=None, max_length=100, verbose_name='昵称')),
                ('picture', models.ImageField(default=None, upload_to='userimg', verbose_name='头像')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='邮箱')),
                ('phone_number', models.CharField(default=None, max_length=11, verbose_name='电话')),
                ('remark', models.CharField(default=None, max_length=50, verbose_name='签名')),
            ],
        ),
    ]
